//program for KBC

// Question no.1 who is "cristiano Ronaldo"             // 500000 /-
// a = footballer b = actor c = doctor d = engineer 
var a = 2
switch (a) {
    case 1:
        console.log("footballer = correct")
        break;
    case 2:
        console.log("actor = wrong")
        break;
    case 3:
        console.log("doctor = wrong")
        break;
    case 4:
        console.log("engineer = wrong")
        break;    
    default:
        console.log("not an option")
        break;
}
// Question no.2 which is the oldest civilization in the world       // 10000000 /-
// a = harappa b = mohan jo daro c = mesopotamia d = indus valley
var b = 2
switch (b) {
    case 1:
        console.log("harappa = wrong")
         break;
    case 2:
        console.log("mohan jo daro = wrong")
        break;
    case 3:
        console.log("mesopotamia = correct")
        break;
    case 4:
        console.log("indus valley = wrong") 
        break;

    default:
        console.log("not an option")
        break;
}

// Question no.3 which is the largest marine creature in the world         // 20000000 /-
// a = great white shark b = blue whale  c = shark whale d = giant squid

var c = 1
switch (c ) {
    case 1:
        console.log("great white shark = wrong")
        break;
    case 2:
        console.log("blue whale = correct")
        break;

    case 3:
        console.log("whale shark = wrong")
        break;

    case 4:
        console.log(" giant squid = wrong")
        break;
    default:
        console.log("not an option")
        break;
}

//question no.4 wwhich scientist create a first nuclear bomb              // 30000000 /-
//a = openheimer b = edward taller c = klaus fuchs d = albert einstien

var d = 1
switch (d ) {
    case 1:
        console.log("openheimer = correct")
        break;
    case 2:
        console.log("edward taller = wrong")
        break;

    case 3:
        console.log("klaus fuchs = wrong")
        break;

    case 4:
        console.log("elbert einstien = wrong")
        break;
    default:
        console.log("not an option")
        break;
}
 
// Question no. 5 which is the biggest threat to planet earth               // 70000000 /-
// a = nuclear plants b = global warming c = pandamic virus d = Humans 

var e = 1
switch (e ) {
    case 1:
        console.log("nuclear plants = wrong")
        break;
    case 2:
        console.log("global warming = wrong")
        break;

    case 3:
        console.log("pandemic virus = wrong")
        break;

    case 4:
        console.log("Humans= correct")
        break;
    default:
        console.log("not an option")
        break;
}


console.log("\\>>>")

console.log("correct answers are :- a/1 footballer , b/3 masopotamia , c/2 blue whale , d/1 openheimer , e/4 Humans")