//program for KBC

// Question no.1 who is "cristiano Ronaldo"             // 500000 /-
// a = footballer b = actor c = doctor d = engineer 
 
var a= 'footballer'
if(a== 'footballer'){
    console.log("corect answer")
}else {
    console.log("wrong answer")
}

// Question no.2 which is the oldest civilization in the world       // 10000000 /-
// a = harappa b = mohan jo daro c = mesopotamia d = indus valley

var c= 'mesopotamia'
if (c=='mesopotamia'){
    console.log("correct answer")
}else {
    console.log("wrong answer")
}

// Question no.3 which is the largest marine creature in the world         // 20000000 /-
// a = great white shark b = blue whale  c = shark whale d = giant squid

var b = 'blue whale'
if (b=='blue whale'){
    console.log("correct answer")
}else {
    console.log("wrong answer")
}

//question no.4 wwhich scientist create a first nuclear bomb              // 30000000 /-
//a = openheimer b = edward taller c = klaus fuchs d = albert einstien

var a= 'openheimer'
if (a=='openheimer'){
    console.log("correct answer")
}else {
    console.log(" wrong answer")
}
 
// Question no. 5 which is the biggest threat to planet earth               // 70000000 /-
// a = nuclear plants b = global warming c = pandamic virus d = Humans 

var a = 'nuclear plants'
if (a=='Humans'){
    console.log( "correct answer")
}else {
    console.log("wrong answer")
}